version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: chat-bot
    restart: always
    env_file:
      - bot/.env
    depends_on:
      - redis

  celery:
    build: .
    container_name: chat-bot-celery
    command: celery -A bot.tasks worker --loglevel=info
    env_file:
      - bot/.env
    depends_on:
      - redis
